#!/usr/bin/env node
/**
 * agents/tracking-concept-generator/run.js
 *
 * Reads a merged analytics spec YAML and generates one implementation
 * Markdown doc per event (also know as tracking concept), writing to tracking-concepts/<event_name>.md
 *
 * Usage (CI):
 *   node agents/tracking-concept-generator/run.js --spec specs/SPEC-2025-001.yaml
 *
 * Usage (local):
 *   ANTHROPIC_API_KEY=sk-... node agents/tracking-concept-generator/run.js --spec specs/SPEC-2025-001.yaml
 *
 * Env vars:
 *   ANTHROPIC_API_KEY  — required
 *   OUTPUT_DIR         — override output directory (default: tracking-concepts/)
 *   DEBUG=1            — verbose stderr logging
 */

import { readFileSync, mkdirSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");
const PROMPT_PATH = join(__dirname, "prompt.md");
const MODEL = "claude-opus-4-5";
const MAX_TOKENS = 4096;

// ── CLI args ──────────────────────────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  const specIdx = args.indexOf("--spec");
  if (specIdx === -1 || !args[specIdx + 1]) {
    console.error("Usage: node run.js --spec <path/to/spec.yaml>");
    process.exit(1);
  }
  return { specPath: args[specIdx + 1] };
}

// ── Spec loader ───────────────────────────────────────────────────────────────

function loadSpec(relPath) {
  const absPath = join(REPO_ROOT, relPath);
  if (!existsSync(absPath)) {
    throw new Error(`Spec file not found: ${absPath}`);
  }
  const raw = readFileSync(absPath, "utf8");
  const sanitized = raw.replace(
    /^(\s*[\w.]+\s*):\s*(NEEDS_CLARIFICATION:[^\n]+)$/gm,
    '$1: "$2"'
  );
  const parsed = parseYaml(sanitized);

  if (!parsed.events || !Array.isArray(parsed.events)) {
    throw new Error("Spec must contain a top-level 'events' array.");
  }

  if (process.env.DEBUG) {
    console.error(`[tracking-concept-generator] Loaded spec: ${parsed.spec_id ?? "(no spec_id)"}`);
    console.error(`[tracking-concept-generator] Events found: ${parsed.events.map((e) => e.name).join(", ")}`);
  }

  return parsed;
}

// ── Claude API call ───────────────────────────────────────────────────────────

async function callClaude(systemPrompt, userContent) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set.");

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: systemPrompt,
      messages: [{ role: "user", content: userContent }],
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Claude API ${response.status}: ${body}`);
  }

  const data = await response.json();
  const textBlocks = data.content.filter((b) => b.type === "text");
  if (!textBlocks.length) throw new Error("Claude returned no text content.");
  return textBlocks.map((b) => b.text).join("\n");
}

// ── Per-event doc generation ──────────────────────────────────────────────────

function buildUserMessage(spec, event) {
  // Send full spec context + isolated event block for clarity
  const eventYaml = stringifyYaml({ event });
  const specMeta = stringifyYaml({
    spec_id: spec.spec_id,
    title: spec.title,
    platform: spec.platform,
    global_parameters: spec.global_parameters ?? [],
  });

  return [
    "## Spec Metadata",
    "```yaml",
    specMeta,
    "```",
    "",
    "## Event to Document",
    "```yaml",
    eventYaml,
    "```",
    "",
    "Generate the tracking concept (implementation guide for devs) document for this event only.",
    "Apply any global_parameters as implicit context (they are sent on every hit).",
  ].join("\n");
}

async function generateDocForEvent(systemPrompt, spec, event) {
  const userMessage = buildUserMessage(spec, event);

  if (process.env.DEBUG) {
    console.error(`[tracking-concept-generator] → Calling Claude for event: ${event.name}`);
  }

  const markdown = await callClaude(systemPrompt, userMessage);
  return markdown.trim();
}

// ── Output writer ─────────────────────────────────────────────────────────────

function writeDoc(eventName, markdown) {
  const outputDir = process.env.OUTPUT_DIR ?? join(REPO_ROOT, "tracking-concepts");
  mkdirSync(outputDir, { recursive: true });

  const fileName = `${eventName}.md`;
  const filePath = join(outputDir, fileName);

  const header = [
    "<!--",
    `  Auto-generated by web-tracking-cicd tracking-concept-generator`,
    `  Event: ${eventName}`,
    `  Generated: ${new Date().toISOString()}`,
    `  DO NOT EDIT — regenerate by re-running the spec through CI`,
    "-->",
    "",
  ].join("\n");

  writeFileSync(filePath, header + markdown + "\n", "utf8");
  console.log(`[tracking-concept-generator] ✓ Written: ${filePath}`);
  return filePath;
}

// ── Entrypoint ────────────────────────────────────────────────────────────────

async function main() {
  const { specPath } = parseArgs();

  // Load system prompt
  const systemPrompt = readFileSync(PROMPT_PATH, "utf8");

  // Load spec
  let spec;
  try {
    spec = loadSpec(specPath);
  } catch (err) {
    console.error(`[tracking-concept-generator] Spec load error: ${err.message}`);
    process.exit(1);
  }

  const events = spec.events;
  console.error(`[tracking-concept-generator] Generating docs for ${events.length} event(s)...`);

  const results = { written: [], failed: [] };

  // Process events sequentially to avoid rate-limit spikes
  for (const event of events) {
    try {
      const markdown = await generateDocForEvent(systemPrompt, spec, event);
      const filePath = writeDoc(event.name, markdown);
      results.written.push({ event: event.name, file: filePath });
    } catch (err) {
      console.error(`[tracking-concept-generator] ✗ Failed for ${event.name}: ${err.message}`);
      results.failed.push({ event: event.name, error: err.message });
    }
  }

  // Summary
  console.error(`\n[tracking-concept-generator] Summary:`);
  console.error(`  ✓ ${results.written.length} doc(s) written`);
  if (results.failed.length) {
    console.error(`  ✗ ${results.failed.length} failed:`);
    results.failed.forEach((f) => console.error(`    - ${f.event}: ${f.error}`));
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(`[tracking-concept-generator] Unexpected error: ${err.message}`);
  process.exit(1);
});
